version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.15.3
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'

      # Download, cache depdencies, using fallback to latest if none found
      - restore_cache: 
          keys: 
            - dependency-cache-{{ checksum "package-lock.json" }}
            - dependency-cache-
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: test
          command: npm test
      - store_artifacts:
          path: coverage